spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/MemberdbRealm
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs


jwt:
  auth:
    converter:
      resource-id: member-api
      principle-attribute: preferred_username
